### ISSUE TITLE
capital error

### ISSUE THREAD

**Issue by JLTrincado** [ykat0/capital#2]
Dear authors,

thanks for solving the previous issue. I proceeded as you suggested via scanpy and I ran successfully the pre_processing step, but I encounter the following error in the next step:

```
/home/trincadojl/Software/capital-0.2.0/capital.py ./processed_data_WT/filtered_feature_bc_matrix.WT.h5ad ./processed_data_KO/filtered_feature_bc_matrix.KO.h5ad 6 10 /media/trincadojl/data/Projects/GUIL/tables/genes_CAPITAL.tsv
AnnData object with n_obs × n_vars = 30893 × 2000
    obs: 'n_genes', 'leiden'
    var: 'gene_ids', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'leiden', 'leiden_colors', 'leiden_sizes', 'neighbors', 'paga', 'pca', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

AnnData object with n_obs × n_vars = 41831 × 1999
    obs: 'n_genes', 'leiden'
    var: 'gene_ids', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'leiden', 'leiden_colors', 'leiden_sizes', 'neighbors', 'paga', 'pca', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

704 genes are used to calculate cost of tree alignment.

Computing dynamic time warping for each gene.
Progress:   0%|                                                                                          | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/trincadojl/Software/capital-0.2.0/capital.py", line 141, in <module>
    results = dtw.dpt_dtw(data1, data2, calculated_data.alignedtree, gene, localalign=args.local_align)
  File "/home/trincadojl/Software/capital-0.2.0/main.py", line 1055, in dpt_dtw
    result_list = self.applying_dtw_to_one_path(data1, data2, alignedtree, dtw_cluster_list, genename)
  File "/home/trincadojl/Software/capital-0.2.0/main.py", line 999, in applying_dtw_to_one_path
    data_dpt1 = self.dpt(data1, real_nodes1)
  File "/home/trincadojl/Software/capital-0.2.0/main.py", line 947, in dpt
    distancearray = dist.pairwise(adata_dpt.X)
  File "sklearn/neighbors/_dist_metrics.pyx", line 388, in sklearn.neighbors._dist_metrics.DistanceMetric.pairwise
  File "/home/trincadojl/anaconda3/envs/capital/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

I selected two genes that I know are among the variable genes in both datasets (TOP2A and AQP4). I've created a conda environment following your instructions.

Thanks for your help.
Best regards.

Juan L.

**Comment by ykat0** [comment]
Dear Juan,

Sorry for the late answer.

We have not been able to reproduce the same error, but specified the part that may cause the bug.
We are still going on with the improvement, and thank you for your patience.

BW,

Yuki

**Comment by ykat0** [comment]
Dear Juan,

We have released CAPITAL ver. 0.2.1, which is expected to address your issue.

BW,

Yuki

**Comment by JLTrincado** [comment]
Dear Yuki,

Thanks for the reply. I installed everything but I'm afraid I'm getting same error:

```
/home/trincadojl/Software/capital/capital-0.2.1/capital.py ./processed_data_WT/filtered_feature_bc_matrix.WT.h5ad ./processed_data_KO/filtered_feature_bc_matrix.KO.h5ad 6 10 /media/trincadojl/data/Projects/GUIL/tables/genes_CAPITAL.tsv

AnnData object with n_obs × n_vars = 30893 × 2000
    obs: 'n_genes', 'leiden'
    var: 'gene_ids', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'leiden', 'leiden_colors', 'leiden_sizes', 'neighbors', 'paga', 'pca', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

AnnData object with n_obs × n_vars = 41831 × 1999
    obs: 'n_genes', 'leiden'
    var: 'gene_ids', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'leiden', 'leiden_colors', 'leiden_sizes', 'neighbors', 'paga', 'pca', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

704 genes are used to calculate cost of tree alignment.

Computing dynamic time warping for each gene.
Progress:   0%|                                                                                                                                                                                                                                           | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/trincadojl/Software/capital/capital-0.2.1/capital.py", line 157, in <module>
    results = dtw.dpt_dtw(
  File "/home/trincadojl/Software/capital/capital-0.2.1/main.py", line 1131, in dpt_dtw
    result_list = self.applying_dtw_to_one_path(
  File "/home/trincadojl/Software/capital/capital-0.2.1/main.py", line 1063, in applying_dtw_to_one_path
    data_dpt1 = self.dpt(data1, real_nodes1)
  File "/home/trincadojl/Software/capital/capital-0.2.1/main.py", line 1002, in dpt
    distancearray = dist.pairwise(adata_dpt.X)
  File "sklearn/neighbors/_dist_metrics.pyx", line 388, in sklearn.neighbors._dist_metrics.DistanceMetric.pairwise
  File "/home/trincadojl/anaconda3/envs/capital/lib/python3.8/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

Not sure where this error comes from.

Thanks for the follow-up.
Best,

Juan L.,

**Comment by ykat0** [comment]
Dear Juan,

The error seemed to occur when calculating dynamic time warping for the first gene that you specified in your TSV file. Could you possibly show me the content of "genes_CAPITAL.tsv," or just a part of it? Does it follow the format of one gene per line?

BW,

Yuki

**Comment by JLTrincado** [comment]
Dear Yuki,

Yes, this is my genes.tsv file:

TOP2A
AQP4

I'm sure these 2 genes are in both files.

Thanks again for your time.
Best,

Juan L.

**Comment by ykat0** [comment]
Dear Juan,

We have not yet been able to reproduce the error, but we think it may be due to handling sparse data when calculating dynamic time warping. We still try pinning it down.

Many thanks for your patience.

BW,

Yuki

**Comment by ykat0** [comment]
Dear Juan,

We are very sorry to have kept you waiting so long. Finally, we have released ver. 0.2.2, where 10x Genomics data can be dealt with properly. I hope your problem will be sorted out.

Cheers,

Yuki
